#---------------------------------------------------------#
#
# Mainly to establish german as default language
#
# see https://www.thomaskieslich.de/blog/127-typo3-8x-ckeditor-konfigurieren/
# see https://www.clickstorm.de/blog/der-neue-typo3-rte-ckeditor/
# see https://usetypo3.com/ckeditor.html
#
#---------------------------------------------------------#

imports:
  - { resource: "EXT:bootstrap_package/Configuration/RTE/Default.yaml" }

editor:
  config:
    defaultContentLanguage: "de"
    defaultLanguage: "de"
    extraAllowedContent:
      - code
      - div
      - span
      - "*(*)"
      - "*[data-*]"
    stylesSet:
      - { name: "Button Complementary", element: "a", attributes: { 'class': 'btn btn-complementary' } }
      - { name: "Button Light", element: "a", attributes: { 'class': 'btn btn-light' } }
      - { name: "Button Dark", element: "a", attributes: { 'class': 'btn btn-dark' } }

      - { name: "Button Outline Complementary", element: "a", attributes: { 'class': 'btn btn-outline-complementary' } }
      - { name: "Button Outline Light", element: "a", attributes: { 'class': 'btn btn-outline-light' } }
      - { name: "Button Outline Dark", element: "a", attributes: { 'class': 'btn btn-outline-dark' } }

      - { name: "Complementary", element: "span", attributes: { 'class': 'text-complementary' } }
      - { name: "Code", element: "code" }
      - { name: "Popover", element: "a", attributes: { 'class': 'pp-popover' } }

classesAnchor:
  page-arrow:
    class: 'link-arrow'
    type: 'page'
  folder-arrow:
    class: 'link-arrow'
    type: 'folder'
  file-arrow:
    class: 'link-arrow'
    type: 'file'
  external-arrow:
    class: 'link-arrow'
    type: 'url'
  mail-arrow:
    class: 'link-arrow'
    type: 'mail'
  pppopover-arrow:
    class: 'link-arrow'
    type: 'pppopover'
  pppopover:
    class: 'pp-popover'
    type: 'pppopover'

buttons:
  link:
    pppopover:
      properties:
        class:
          default: 'pp-popover'
    properties:
      class:
        allowedClasses: 'link-arrow, link-page, link-folder, link-file, link-external, link-mail, pp-popover'

classes:
  link-arrow:
    name: 'Arrow link'
  link-page:
    name: 'Page link'
  link-folder:
    name: 'Folder link'
  link-file:
    name: 'File link'
  link-external:
    name: 'External link'
  link-mail:
    name: 'Mail link'
  pp-popover:
    name: 'Popover'

processing:
  entryHTMLparser_db:
    keepNonMatchedTags: 1
    tags:
      a:
        fixAttrib:
          href:
            userFunc: 'Buepro\Pizpalue\UserFunction\HtmlParser\TagModifier->fixATagHrefAttribute'
