services:
  Buepro\Pizpalue\Service\BrandingService:
    tags:
      - name: event.listener
        identifier: 'buepro/pizpalue/set-backend-styling'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionFilesHaveBeenImportedEvent
  Buepro\Pizpalue\Backend\ToolbarItem\VersionToolbarItem:
    tags:
      -
        name: event.listener
        identifier: 'buepro/pizpalue/add-version-information'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
  Buepro\Pizpalue\Service\ExtensionInstallService:
    tags:
      - name: event.listener
        identifier: 'buepro/pizpalue/finalize-extension-installation'
        event: TYPO3\CMS\Extensionmanager\Event\AfterExtensionFilesHaveBeenImportedEvent
