name: CI

on:
  push:
    paths:
      - '**.php'
      - '.github/workflows/**'
    branches-ignore:
      - 'l10n**'
  pull_request:
    branches-ignore:
      - 'l10n**'

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        typo3: [ '^12' ]
        php: [ '8.1', '8.2', '8.3' ]
        mysql: [ '8.0' ]
    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: setup_mysql
        name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'
      - id: setup_php
        name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Composer Cache Vars
        id: composer-cache-vars
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +"%s")" >> $GITHUB_OUTPUT
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-vars.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.typo3 }}-${{ steps.composer-cache-vars.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.typo3 }}-
            ${{ runner.os }}-composer-${{ matrix.php }}-
            ${{ runner.os }}-composer-
      - id: install
        name: Install
        run: |
          composer remove --dev --no-update buepro/typo3-container-elements buepro/typo3-user-pizpalue friendsoftypo3/tt-address georgringer/eventnews georgringer/news
          composer require typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json
          [ -d .build/public/typo3/sysext/dummy ] || mkdir -p .build/public/typo3/sysext/dummy
      - id: cgl
        name: CGL
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer ci:php:cs
      - id: lint
        name: Lint
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer ci:php:lint
      - id: phpstan
        name: PHPStan
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer ci:php:stan -- --error-format=github
      - id: tests_unit
        name: Unit Tests
        run: |
          composer ci:tests:unit
